#define PIP_SCOPE(KLS) KLS = KLS

// Eotech
PIP_SCOPE(CUP_optic_G33_HWS_BLK);
PIP_SCOPE(CUP_optic_G33_HWS_TAN);
PIP_SCOPE(CUP_optic_G33_HWS_OD);
PIP_SCOPE(CUP_optic_G33_HWS_COYOTE);

// Aimpoint
PIP_SCOPE(CUP_optic_AIMM_MICROT1_BLK);
PIP_SCOPE(CUP_optic_AIMM_MICROT1_TAN);
PIP_SCOPE(CUP_optic_AIMM_MICROT1_OD);

PIP_SCOPE(CUP_optic_AIMM_COMPM4_BLK);

PIP_SCOPE(CUP_optic_AIMM_COMPM2_BLK);
PIP_SCOPE(CUP_optic_AIMM_COMPM2_TAN);
PIP_SCOPE(CUP_optic_AIMM_COMPM2_OD);

PIP_SCOPE(CUP_optic_AIMM_M68_BLK);
PIP_SCOPE(CUP_optic_AIMM_M68_TAN);
PIP_SCOPE(CUP_optic_AIMM_M68_OD);

// MARS
PIP_SCOPE(CUP_optic_AIMM_MARS_BLK);
PIP_SCOPE(CUP_optic_AIMM_MARS_TAN);
PIP_SCOPE(CUP_optic_AIMM_MARS_OD);

// ZD
PIP_SCOPE(CUP_optic_AIMM_ZDDOT_BLK);